<pre><code><span class="code-light"><</span><span class="light-pink-code">div</span> <span class="code-blue">class</span><span class="code-light">=</span><span class="code-pink">"fish-tank"</span><span class="code-light">></span>
    <span class="code-light"><</span><span class="light-pink-code">div</span> <span class="code-blue">class</span><span class="code-light">=</span><span class="code-pink">"fish"</span> <span class="code-blue">data-aos</span><span class="code-light">=</span><span class="code-pink">"fade-down"</span> <span class="code-blue">data-aos-easing</span><span class="code-light">=</span><span class="code-pink">"linear"</span> <span class="code-blue">data-aos-duration</span><span class="code-light">=</span><span class="code-pink">"1500"</span><span class="code-light">></span> <span class="code-comment">&lt;!-- scroll animation options --></span>
    <span class="code-light">...</span>
    <span class="code-light"><</span><span class="light-pink-code">/div</span><span class="code-light">></span>
    <span class="code-light"><</span><span class="light-pink-code">div</span> <span class="code-blue">class</span><span class="code-light">=</span><span class="code-pink">"fish"</span> <span class="code-blue">data-aos</span><span class="code-light">=</span><span class="code-pink">"fade-down"</span> <span class="code-blue">data-aos-easing</span><span class="code-light">=</span><span class="code-pink">"linear"</span> <span class="code-blue">data-aos-duration</span><span class="code-light">=</span><span class="code-pink">"1500"</span><span class="code-light">></span> <span class="code-comment">&lt;!-- scroll animation options --></span>
    <span class="code-light">...</span>
    <span class="code-light"><</span><span class="light-pink-code">/div</span><span class="code-light">></span>
    <span class="code-light"><</span><span class="light-pink-code">div</span> <span class="code-blue">class</span><span class="code-light">=</span><span class="code-pink">"fish"</span> <span class="code-blue">data-aos</span><span class="code-light">=</span><span class="code-pink">"fade-down"</span> <span class="code-blue">data-aos-easing</span><span class="code-light">=</span><span class="code-pink">"linear"</span> <span class="code-blue">data-aos-duration</span><span class="code-light">=</span><span class="code-pink">"1500"</span><span class="code-light">></span> <span class="code-comment">&lt;!-- scroll animation options --></span>
    <span class="code-light">...</span>
    <span class="code-light"><</span><span class="light-pink-code">/div</span><span class="code-light">></span>
    <span class="code-light"><</span><span class="light-pink-code">div</span> <span class="code-blue">class</span><span class="code-light">=</span><span class="code-pink">"fish"</span> <span class="code-blue">data-aos</span><span class="code-light">=</span><span class="code-pink">"fade-down"</span> <span class="code-blue">data-aos-easing</span><span class="code-light">=</span><span class="code-pink">"linear"</span> <span class="code-blue">data-aos-duration</span><span class="code-light">=</span><span class="code-pink">"1500"</span><span class="code-light">></span> <span class="code-comment">&lt;!-- scroll animation options --></span>
    <span class="code-light">...</span>
    <span class="code-light"><</span><span class="light-pink-code">/div</span><span class="code-light">></span>
    <span class="code-light"><</span><span class="light-pink-code">div</span> <span class="code-blue">class</span><span class="code-light">=</span><span class="code-pink">"fish"</span> <span class="code-blue">data-aos</span><span class="code-light">=</span><span class="code-pink">"fade-down"</span> <span class="code-blue">data-aos-easing</span><span class="code-light">=</span><span class="code-pink">"linear"</span> <span class="code-blue">data-aos-duration</span><span class="code-light">=</span><span class="code-pink">"1500"</span><span class="code-light">></span> <span class="code-comment">&lt;!-- scroll animation options --></span>
    <span class="code-light">...</span>
    <span class="code-light"><</span><span class="light-pink-code">/div</span><span class="code-light">></span>
    <span class="code-light"><</span><span class="light-pink-code">/div</span><span class="code-light">></span>
    
    <span class="code-comment">&lt;!-- Scroll Reveal --></span>
    <span class="code-light"><</span><span class="light-pink-code">script</span> <span class="code-blue">src</span><span class="code-light">=</span><span class="code-pink">"https://unpkg.com/aos@2.3.1/dist/aos.js"</span><span class="code-light">></span><span class="code-light"><</span><span class="light-pink-code">/script</span><span class="code-light">></span>
    
    <span class="code-comment">&lt;!-- Initialize Scroll Reveal --></span>
    <span class="code-light"><</span><span class="light-pink-code">script</span><span class="code-light">></span>
    <span class="code-blue">AOS</span><span class="code-light">.</span><span class="code-blue">init</span><span class="code-light">();</span>
    <span class="code-light"><</span><span class="light-pink-code">/script</span><span class="code-light">></span>
</code></pre>